# Generated by Django 4.2 on 2025-10-31 21:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('game_system', models.CharField(default='Warhammer 40,000', help_text='e.g. 40k, AoS, Kill Team, Heresy', max_length=100)),
                ('points_level', models.CharField(blank=True, help_text='e.g. 1000pts, Combat Patrol, 2k, 750 narrative', max_length=50)),
                ('organiser', models.CharField(max_length=100)),
                ('organiser_contact', models.CharField(blank=True, max_length=100)),
                ('start_time', models.DateTimeField()),
                ('max_players', models.PositiveIntegerField(default=2)),
                ('current_players', models.PositiveIntegerField(default=1)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='warhammer.venue')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
