# Generated by Django 4.2 on 2025-10-31 22:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='area',
        ),
        migrations.AddField(
            model_name='venue',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
