# Generated by Django 4.2 on 2025-10-31 22:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0002_remove_venue_area_venue_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
