# Generated by Django 4.2 on 2025-11-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0003_alter_gamesession_location'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['location'], name='warhammer_g_locatio_a12a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['venue'], name='warhammer_g_venue_i_a79e29_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['location'], name='warhammer_v_locatio_5d83fb_idx'),
        ),
    ]
