# Generated by Django 4.2 on 2025-11-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0005_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
